runtime:
  logging_level: "debug"
project:
  image_dir: "./vinepilot/data/imgs"
  data: "./vinepilot/data/data.json"
  vineyards_dir: "./vinepilot/data/vineyards"
  model_dir: "./vinepilot/model" 
  model_weights: "./vinepilot/model/best_model.pth"
train:
  batch_size: 5
  epochs: 3
  shuffle: True
  optimizer: "adam"
  loss: "mse"
  learning_rate: 0.001