runtime:
  logging_level: "info"
dataset:
  image_dir: "./vinepilot/data/imgs"
  data: "./vinepilot/data/data.json"
  vineyards_dir: "./vinepilot/data/vineyards"
train:
  batch_size: 1
  epochs: 3
  shuffle: False
  optimizer: "adam"
  learning_rate: 0.001
  loss: "mse"
test:
server:
  host_address: "192.168.114.132"
  port: 8000