runtime:
  logging_level: "debug"
project:
  image_dir: "./vinepilot/data/imgs"
  data: "./vinepilot/data/data.json"
  vineyards_dir: "./vinepilot/data/vineyards"
  model_dir: "./vinepilot/model" 
train:
  batch_size: 5
  epochs: 3
  shuffle: True
  optimizer: "adam"
  loss: "mse"
  learning_rate: 0.01
test:
server:
  host_address: "192.168.114.132"
  port: 8000